import { formatDate, escapeHtml, icon } from './utils.js';

const columns = [
  ['expand','',30],
  ['id','UniqueID',85],['submitted','Submitted Date',136],['requester','Requested Name',141],['designation','Designation',120],['region','Location / Region',96],['type','Request Type',126],['description','Description',150],['eta','ETA (mins.)',68],['deadline','Deadline Date',95],['deadlineTime','Deadline Time',72],['priority','Priority',72],['attachments','',42],['mail','',42],['assign','Assign',78],['project','Project',54],['urgent','Urgent Request',65],['actions','',42]
];
const priorityClass = p => `priority-${p.toLowerCase()}`;
const value = (request, key) => key === 'submitted' || key === 'deadline' || key === 'deadlineTime' ? new Date(request.deadline).valueOf() : request[key] ?? '';

export function renderQueue(state, view) {
  const requests = filteredRequests(state.queue, view);
  const pageSize = Number(view.pageSize);
  const maxPage = Math.max(1, Math.ceil(requests.length / pageSize));
  view.page = Math.min(view.page, maxPage);
  const rows = requests.slice((view.page - 1) * pageSize, view.page * pageSize);
  return `<section class="queue-card">
    <div class="queue-controls"><select class="page-size" aria-label="Rows per page">${[10,20,50,100].map(n=>`<option ${n===pageSize?'selected':''}>${n}</option>`).join('')}</select><span class="rows-label">Rows per page</span><div class="pagination"><button data-page="first" ${view.page===1?'disabled':''}>«</button><button data-page="prev" ${view.page===1?'disabled':''}>‹</button>${pageButtons(view.page,maxPage)}<button data-page="next" ${view.page===maxPage?'disabled':''}>›</button><button data-page="last" ${view.page===maxPage?'disabled':''}>»</button></div><span class="control-spacer"></span><label class="search"><span class="sr-only">Search requests</span><input id="queue-search" placeholder="Search..." value="${escapeHtml(view.search)}">${icon('search',20)}</label><button class="new-request">${icon('mail',25)} Add New Request</button></div>
    ${filterBar(view)}<div class="table-scroll"><table class="request-table"><thead><tr>${columns.map(([key,label,width])=>`<th style="width:${width}px" class="${['attachments','mail','assign','project','urgent','actions'].includes(key)?'':'sortable'}" data-sort="${key}">${label ? escapeHtml(label) : (key==='attachments'?icon('clip',21):key==='mail'?icon('mail',23):'')} ${!['attachments','mail','assign','project','urgent','actions'].includes(key)?`<span class="sort-mark">${view.sort.key===key?(view.sort.direction==='asc'?'▲':'▼'):'◆'}</span>`:''}</th>`).join('')}</tr></thead><tbody>${rows.length ? rows.map(row).join('') : `<tr><td colspan="17" class="empty">No requests match the selected criteria.</td></tr>`}</tbody></table></div><div class="results">Showing results ${requests.length ? (view.page-1)*pageSize+1 : 0} - ${Math.min(view.page*pageSize,requests.length)} of ${requests.length} items</div></section>`;
}

function pageButtons(page, max) { return Array.from({length:Math.min(max,3)},(_,i)=>{ const p = Math.max(1, Math.min(max, page - 1 + i)); return `<button data-page="${p}" class="${p===page?'current':''}">${p}</button>`; }).filter((x,i,a)=>a.indexOf(x)===i).join(''); }
function row(r) { const deadline=new Date(r.deadline); const date=deadline.toLocaleDateString('en-GB'); const time=deadline.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false}); return `<tr class="clickable-row" data-open-request="${r.id}"><td class="expand">▶</td><td class="request-id">${r.id}</td><td>${formatDate(r.submitted)}</td><td>${escapeHtml(r.requester)}</td><td>${escapeHtml(r.designation)}</td><td>${escapeHtml(r.region)}</td><td>${escapeHtml(r.type)}</td><td>${escapeHtml(r.description)}</td><td>${r.eta}</td><td>${date}</td><td>${time}</td><td class="priority-cell"><span class="badge ${priorityClass(r.priority)}">${r.priority}</span></td><td class="icon-cell">${icon('clip',19)}</td><td class="icon-cell">${icon('mail',21)}</td><td><button class="assign" data-assign="${r.id}">Assign</button></td><td class="icon-cell"><input class="checkbox" type="checkbox" aria-label="Mark ${r.id} project"></td><td class="icon-cell"><input class="checkbox" type="checkbox" aria-label="Mark ${r.id} urgent"></td><td><details class="request-menu"><summary>☰</summary><div><button data-request-action="hold" data-request-id="${r.id}">Put on hold</button><button data-request-action="cancel" data-request-id="${r.id}">Cancel request</button><button data-request-action="add" data-request-id="${r.id}">Add request</button></div></details></td></tr>`; }
function filterBar(view) { const opts = (values, selected, label, key) => `<select data-filter="${key}"><option value="">All ${label}</option>${values.map(v=>`<option value="${escapeHtml(v)}" ${selected===v?'selected':''}>${escapeHtml(v)}</option>`).join('')}</select>`; return `<div class="filterbar"><label>Filters</label>${opts(['Critical','High','Medium','Low'],view.filters.priority,'Priority','priority')}${opts(['Americas','Asia-Pacific','Europe'],view.filters.region,'Region','region')}${opts(['Investment Banking','Markets','Corporate Banking','Wealth Management'],view.filters.business,'Business','business')}${opts(['Company Research','Industry Research','Market Research','Deal Research','Adverse News','Quick Request'],view.filters.type,'Request Type','type')}<button data-clear-filters>Clear filters</button></div>`; }
export function filteredRequests(requests, view) { const q = view.search.trim().toLowerCase(); const out = requests.filter(r => (!q || [r.id,r.company,r.requester,r.type,r.region,r.researcher].join(' ').toLowerCase().includes(q)) && Object.entries(view.filters).every(([k,v])=>!v || r[k]===v)); return out.sort((a,b) => { const x=value(a,view.sort.key),y=value(b,view.sort.key); return (x>y?1:x<y?-1:0)*(view.sort.direction==='asc'?1:-1); }); }
