import { icon, escapeHtml } from './utils.js';

const pinnedTimezones = [
  ['America/New_York', 'New York (ET)'], ['America/Chicago', 'Texas (CT)'], ['America/Los_Angeles', 'California (PT)'], ['Europe/London', 'United Kingdom'], ['Asia/Tokyo', 'Japan'], ['Asia/Shanghai', 'Beijing / China'], ['Asia/Hong_Kong', 'Hong Kong'], ['Asia/Singapore', 'Singapore'], ['Australia/Sydney', 'Sydney'], ['Europe/Paris', 'Central Europe']
];

export function renderShell(content, state, screen) {
  const dayStatus = state.dayStatus || 'Not started';
  return `<div class="app-shell"><header><div class="brand-header"><h1>Information Request Queue</h1><div class="profile"><div class="staffing-summary"><strong>Current Staffer - ____</strong><label>Current QCer - <input class="current-qcer" data-current-qcer value="${escapeHtml(state.currentQcer)}" aria-label="Current QCer"></label></div><span class="divider"></span><div class="clock-zone" aria-label="Deadline time converter"><div class="clock-block"><span class="clock-label">IST · India</span><input class="clock-time-input" type="time" data-ist-time aria-label="IST time"><span class="clock-day" data-ist-day></span></div><div class="clock-block"><span class="clock-label" data-selected-zone>New York (ET)</span><input class="clock-time-input" type="time" data-zone-time aria-label="Selected timezone time"><span class="clock-day" data-zone-day></span></div><select class="timezone-picker" aria-label="Select timezone" data-timezone></select></div><span class="divider"></span><details class="day-menu"><summary aria-label="Workday options"><span class="day-date">26.06.2026</span><span class="day-status">${escapeHtml(dayStatus)}</span></summary><div class="day-menu-options"><button data-day-action="Started">Start Day</button><button data-day-action="On break">Start Break</button><button data-day-action="Working">End Break</button><button data-day-action="Ended">End Day</button></div></details><span class="profile-user">${icon('user', 28)} Profile</span>${icon('calendar', 28)}</div></div><nav class="topnav"><span class="mail">${icon('mail',35)}<b class="mail-badge">3</b></span><span class="nav-separator"></span><button class="nav-item">${icon('list',27)} My timeline</button><span class="nav-separator"></span><button class="nav-item" data-submit-new-request>${icon('file',27)} Submit new request</button><span class="nav-separator"></span><button class="nav-item">${icon('logout',27)} Logout</button></nav><div class="work-status"><span>Work in progress: <strong>262700</strong> &nbsp;-&nbsp; n/a (Production) &nbsp;-&nbsp; Pause work</span><span>Worked: <strong>260 mins</strong> <span class="nav-separator" style="display:inline-block;margin:0 12px;height:19px"></span> Remaining: <strong>220 mins</strong></span></div></header><main class="page">${renderTabs(screen)}${content}</main></div>`;
}

function renderTabs(screen) { const tabs = [['queue','Queue'],['inProgress','In Progress'],['archive','Archive'],['myRequests','My Requests'],['qc','QC'],['onHold','On Hold'],['hours','Hours Due by Shift'],['currentCapacity','Current Capacity']]; return `<div class="tabs screen-tabs">${tabs.map(([id,label]) => `<button class="tab ${screen === id ? 'active' : ''}" ${['queue','archive','myRequests','qc','currentCapacity'].includes(id) ? `data-screen="${id}"` : 'data-unavailable="true"'}>${label}</button>`).join('')}</div>`; }

const partsInZone = (date, zone) => Object.fromEntries(new Intl.DateTimeFormat('en-CA', { timeZone:zone, year:'numeric', month:'2-digit', day:'2-digit', hour:'2-digit', minute:'2-digit', hourCycle:'h23' }).formatToParts(date).filter(item => item.type !== 'literal').map(item => [item.type, Number(item.value)]));
const timeText = (date, zone) => { const parts = partsInZone(date, zone); return `${String(parts.hour).padStart(2,'0')}:${String(parts.minute).padStart(2,'0')}`; };
const dayDifference = (from, to) => Math.round((Date.UTC(to.year,to.month - 1,to.day) - Date.UTC(from.year,from.month - 1,from.day)) / 86400000);
const dayLabel = difference => difference === 0 ? 'Same day' : difference === 1 ? 'Next day' : difference === -1 ? 'Previous day' : `${difference > 0 ? '+' : ''}${difference} days`;
function instantForZoneTime(time, zone) { const [hour, minute] = time.split(':').map(Number); const base = partsInZone(new Date(), zone); const wanted = Date.UTC(base.year,base.month - 1,base.day,hour,minute); let timestamp = wanted; for (let i = 0; i < 3; i++) { const actual = partsInZone(new Date(timestamp), zone); timestamp += wanted - Date.UTC(actual.year,actual.month - 1,actual.day,actual.hour,actual.minute); } return new Date(timestamp); }

export function initialiseClocks() {
  const select = document.querySelector('[data-timezone]'); const istInput = document.querySelector('[data-ist-time]'); const zoneInput = document.querySelector('[data-zone-time]');
  if (!select || !istInput || !zoneInput) return;
  const selected = sessionStorage.getItem('irt.selectedTimezone') || 'America/New_York';
  select.innerHTML = pinnedTimezones.map(([zone,label]) => `<option value="${zone}" ${zone === selected ? 'selected' : ''}>${label}</option>`).join('');
  const selectedName = () => pinnedTimezones.find(([zone]) => zone === select.value)?.[1] || select.value;
  const showFrom = (time, sourceZone) => { if (!time) return; const moment = instantForZoneTime(time, sourceZone); const istParts = partsInZone(moment, 'Asia/Kolkata'); const zoneParts = partsInZone(moment, select.value); istInput.value = timeText(moment, 'Asia/Kolkata'); zoneInput.value = timeText(moment, select.value); document.querySelector('[data-ist-day]').textContent = dayLabel(dayDifference(sourceZone === 'Asia/Kolkata' ? istParts : zoneParts, istParts)); document.querySelector('[data-zone-day]').textContent = dayLabel(dayDifference(sourceZone === 'Asia/Kolkata' ? istParts : zoneParts, zoneParts)); document.querySelector('[data-selected-zone]').textContent = selectedName(); };
  istInput.value = timeText(new Date(), 'Asia/Kolkata');
  showFrom(istInput.value, 'Asia/Kolkata');
  istInput.onchange = () => showFrom(istInput.value, 'Asia/Kolkata');
  zoneInput.onchange = () => showFrom(zoneInput.value, select.value);
  select.onchange = () => { sessionStorage.setItem('irt.selectedTimezone', select.value); showFrom(istInput.value, 'Asia/Kolkata'); };
}

export function showQcReviewDialog(request, onSubmit) { const wrap = document.createElement('div'); wrap.className = 'modal-backdrop'; const ratings = ['Excellent','Good','Fair','Poor']; const templates = ['Missing source citation','Incorrect formatting','Company profile incomplete','Financial data outdated','Duplicate information','Grammar corrections','Missing adverse news','Additional competitor analysis required','Excellent work','Ready for client delivery']; wrap.innerHTML = `<section class="modal" role="dialog" aria-modal="true"><div class="modal-header">QC Review · Request ${request.id}</div><div class="modal-body"><p style="margin-top:0">Researcher: <strong>${escapeHtml(request.researcher)}</strong> · QCer: <strong>${escapeHtml(request.qc)}</strong></p><label class="clock-label" style="color:#506078">Quality rating</label><div class="qc-ratings">${ratings.map(r => `<button class="qc-rating ${request.qcRating === r ? 'selected' : ''}" data-rating="${r}">${r}</button>`).join('')}</div><label class="clock-label" style="color:#506078;margin-top:12px">QC comments</label><textarea class="comment-input" data-qc-comment placeholder="Record findings or use a template..."></textarea><div class="qc-templates">${templates.map(t => `<button data-template="${t}">${t}</button>`).join('')}</div><div class="modal-actions" style="justify-content:flex-start"><button class="primary" data-decision="approve">Approve</button><button data-decision="rework">Send for rework</button><button data-close>Cancel</button></div></div></section>`; document.body.append(wrap); let rating = request.qcRating || ''; wrap.querySelectorAll('[data-rating]').forEach(button => button.onclick = () => { rating = button.dataset.rating; wrap.querySelectorAll('[data-rating]').forEach(item => item.classList.toggle('selected', item === button)); }); wrap.querySelectorAll('[data-template]').forEach(button => button.onclick = () => { const input = wrap.querySelector('[data-qc-comment]'); input.value = input.value ? `${input.value}\n${button.dataset.template}` : button.dataset.template; }); wrap.querySelector('[data-close]').onclick = () => wrap.remove(); wrap.querySelectorAll('[data-decision]').forEach(button => button.onclick = () => { const comment = wrap.querySelector('[data-qc-comment]').value.trim(); if (['Fair','Poor'].includes(rating) && !comment) { alert('QC comments are required for Fair and Poor ratings.'); return; } wrap.remove(); onSubmit({ rating, comment, decision:button.dataset.decision }); }); }

export function showDialog(title, message, onConfirm) { const wrap = document.createElement('div'); wrap.className = 'modal-backdrop'; wrap.innerHTML = `<section class="modal" role="dialog" aria-modal="true"><div class="modal-header">${title}</div><div class="modal-body"><div>${message}</div><div class="modal-actions"><button data-close>Cancel</button><button data-confirm class="primary">Confirm</button></div></div></section>`; document.body.append(wrap); wrap.querySelector('[data-close]').onclick = () => wrap.remove(); wrap.querySelector('[data-confirm]').onclick = () => { wrap.remove(); onConfirm(); }; }
export function showAssignmentDialog(request, researchers, onConfirm) { const wrap = document.createElement('div'); wrap.className = 'modal-backdrop'; wrap.innerHTML = `<section class="modal" role="dialog" aria-modal="true"><div class="modal-header">Assign request ${request.id}</div><div class="modal-body"><p style="margin-top:0">Assign this <strong>${escapeHtml(request.type)}</strong> request to a researcher. Requests outside their sign-off route to QC after production.</p><label style="display:block;font-size:13px;font-weight:600;margin-bottom:6px" for="researcher-choice">Researcher</label><select id="researcher-choice" class="status-select">${researchers.map(name => `<option>${escapeHtml(name)}</option>`).join('')}</select><div class="modal-actions"><button data-close>Cancel</button><button data-confirm class="primary">Assign</button></div></div></section>`; document.body.append(wrap); wrap.querySelector('[data-close]').onclick = () => wrap.remove(); wrap.querySelector('[data-confirm]').onclick = () => { const researcher = wrap.querySelector('#researcher-choice').value; wrap.remove(); onConfirm(researcher); }; }
