import { icon, escapeHtml } from './utils.js';
let clockTimer;
export function renderShell(content, state, screen) { return `<div class="app-shell"><header><div class="brand-header"><h1>Information Request Queue</h1><div class="profile"><div class="staffing-summary"><strong>Current Staffer - ____</strong><label>Current QCer - <input class="current-qcer" data-current-qcer value="${escapeHtml(state.currentQcer)}" aria-label="Current QCer"></label></div><span class="divider"></span><div class="clock-zone"><div class="clock-block"><span class="clock-label">IST · Asia/Kolkata</span><time class="clock-time" data-clock="Asia/Kolkata">--:--:--</time></div><div class="clock-block"><span class="clock-label" data-selected-zone>Selected timezone</span><time class="clock-time" data-clock="UTC">--:--:--</time></div><select class="timezone-picker" aria-label="Select timezone" data-timezone></select></div><span class="divider"></span><span class="profile-user">${icon('user',28)} Profile</span><span class="profile-date">26.06.2026</span>${icon('calendar',28)}</div></div><nav class="topnav"><span class="mail">${icon('mail',35)}<b class="mail-badge">3</b></span><span class="nav-separator"></span><button class="nav-item">${icon('list',27)} My timeline</button><span class="nav-separator"></span><button class="nav-item">${icon('file',27)} Submit new request</button><span class="nav-separator"></span><button class="nav-item">${icon('logout',27)} Logout</button></nav><div class="work-status"><span>Work in progress: <strong>262700</strong> &nbsp;-&nbsp; n/a (Production) &nbsp;-&nbsp; Pause work</span><span>Worked: <strong>260 mins</strong> <span class="nav-separator" style="display:inline-block;margin:0 12px;height:19px"></span> Remaining: <strong>220 mins</strong></span></div></header><main class="page">${renderTabs(screen)}${content}</main></div>`; }

function renderTabs(screen) { const tabs=[['queue','Queue'],['inProgress','In Progress'],['archive','Archive'],['myRequests','My Requests'],['qc','QC'],['onHold','On Hold'],['hours','Hours Due by Shift'],['currentCapacity','Current Capacity']]; return `<div class="tabs screen-tabs">${tabs.map(([id,label])=>`<button class="tab ${screen===id?'active':''}" ${['queue','archive','myRequests','qc','currentCapacity'].includes(id)?`data-screen="${id}"`:`data-unavailable="true"`}>${label}</button>`).join('')}</div>`; }

export function showQcReviewDialog(request, onSubmit) { const wrap=document.createElement('div'); wrap.className='modal-backdrop'; const ratings=['Excellent','Good','Satisfactory','Needs Rework']; const templates=['Missing source citation','Incorrect formatting','Company profile incomplete','Financial data outdated','Duplicate information','Grammar corrections','Missing adverse news','Additional competitor analysis required','Excellent work','Ready for client delivery']; wrap.innerHTML=`<section class="modal" role="dialog" aria-modal="true"><div class="modal-header">QC Review · Request ${request.id}</div><div class="modal-body"><p style="margin-top:0">Researcher: <strong>${request.researcher}</strong> · QCer: <strong>${request.qc}</strong></p><label class="clock-label" style="color:#506078">Quality rating</label><div class="qc-ratings">${ratings.map(r=>`<button class="qc-rating ${request.qcRating===r?'selected':''}" data-rating="${r}">${r}</button>`).join('')}</div><label class="clock-label" style="color:#506078;margin-top:12px">QC comments</label><textarea class="comment-input" data-qc-comment placeholder="Record findings or use a template..."></textarea><div class="qc-templates">${templates.map(t=>`<button data-template="${t}">${t}</button>`).join('')}</div><div class="modal-actions" style="justify-content:flex-start"><button class="primary" data-decision="approve">Approve</button><button data-decision="rework">Send for rework</button><button data-decision="hold">Hold</button><button data-decision="escalate">Escalate</button><button data-close>Cancel</button></div></div></section>`; document.body.append(wrap); let rating=request.qcRating || ''; wrap.querySelectorAll('[data-rating]').forEach(button=>button.onclick=()=>{ rating=button.dataset.rating; wrap.querySelectorAll('[data-rating]').forEach(item=>item.classList.toggle('selected',item===button)); }); wrap.querySelectorAll('[data-template]').forEach(button=>button.onclick=()=>{ const input=wrap.querySelector('[data-qc-comment]'); input.value=input.value?`${input.value}\n${button.dataset.template}`:button.dataset.template; }); wrap.querySelector('[data-close]').onclick=()=>wrap.remove(); wrap.querySelectorAll('[data-decision]').forEach(button=>button.onclick=()=>{ wrap.remove(); onSubmit({ rating, comment:wrap.querySelector('[data-qc-comment]').value.trim(), decision:button.dataset.decision }); }); }

export function initialiseClocks() {
  const select = document.querySelector('[data-timezone]');
  if (!select) return;
  const zones = Intl.supportedValuesOf ? Intl.supportedValuesOf('timeZone') : ['UTC','Europe/London','America/New_York','Asia/Singapore','Asia/Tokyo','Australia/Sydney'];
  const selected = sessionStorage.getItem('irt.selectedTimezone') || 'UTC';
  select.innerHTML = zones.map(zone => `<option value="${zone}" ${zone === selected ? 'selected' : ''}>${zone}</option>`).join('');
  const update = () => {
    document.querySelectorAll('[data-clock]').forEach(clock => { const zone = clock.dataset.clock === 'UTC' ? select.value : clock.dataset.clock; clock.textContent = new Intl.DateTimeFormat('en-GB', { timeZone:zone, hour:'2-digit', minute:'2-digit', second:'2-digit', hour12:false }).format(new Date()); });
    document.querySelector('[data-selected-zone]').textContent = select.value.replace('_', ' ');
  };
  select.onchange = () => { sessionStorage.setItem('irt.selectedTimezone', select.value); update(); };
  update();
  window.clearInterval(clockTimer);
  clockTimer = window.setInterval(update, 1000);
}
export function showDialog(title, message, onConfirm) { const wrap=document.createElement('div'); wrap.className='modal-backdrop'; wrap.innerHTML=`<section class="modal" role="dialog" aria-modal="true"><div class="modal-header">${title}</div><div class="modal-body"><div>${message}</div><div class="modal-actions"><button data-close>Cancel</button><button data-confirm class="primary">Confirm</button></div></div></section>`; document.body.append(wrap); wrap.querySelector('[data-close]').onclick=()=>wrap.remove(); wrap.querySelector('[data-confirm]').onclick=()=>{ wrap.remove(); onConfirm(); }; }

export function showAssignmentDialog(request, researchers, onConfirm) { const wrap=document.createElement('div'); wrap.className='modal-backdrop'; wrap.innerHTML=`<section class="modal" role="dialog" aria-modal="true"><div class="modal-header">Assign request ${request.id}</div><div class="modal-body"><p style="margin-top:0">Assign this <strong>${request.type}</strong> request to a researcher. Requests outside their sign-off route to QC after production.</p><label style="display:block;font-size:13px;font-weight:600;margin-bottom:6px" for="researcher-choice">Researcher</label><select id="researcher-choice" class="status-select">${researchers.map(name=>`<option>${name}</option>`).join('')}</select><div class="modal-actions"><button data-close>Cancel</button><button data-confirm class="primary">Assign</button></div></div></section>`; document.body.append(wrap); wrap.querySelector('[data-close]').onclick=()=>wrap.remove(); wrap.querySelector('[data-confirm]').onclick=()=>{ const researcher=wrap.querySelector('#researcher-choice').value; wrap.remove(); onConfirm(researcher); }; }
