import { researcherProfiles } from './data.js';
import { appendAudit } from './audit.js';

export function researcherProfile(name) { return researcherProfiles.find(profile => profile.name === name); }
export function assignToResearcher(request, researcher, currentQcer) { const profile = researcherProfile(researcher); request.researcher=researcher; request.qc=currentQcer || profile?.qc || 'Unassigned'; request.staffer='Current Staffer'; request.requiresQC=!(profile?.signoffs || []).includes(request.type); request.status='Assigned'; request.workflowStage='production'; appendAudit(request,`Assigned to ${researcher} by Current Staffer${request.requiresQC ? ` · QC review required: ${request.qc}` : ' · Production-only sign-off'}`); }
export function currentWorkMinutes(request) { if (!request.timerStartedAt) return request.workMinutes || 0; return (request.workMinutes || 0) + Math.max(0, Math.floor((Date.now() - new Date(request.timerStartedAt).valueOf()) / 60000)); }
export function startWork(request) { if (!request.timerStartedAt) { request.timerStartedAt=new Date().toISOString(); request.status='In Progress'; appendAudit(request,'Production timer started'); } }
export function pauseWork(request) { request.workMinutes=currentWorkMinutes(request); request.timerStartedAt=null; request.status='Paused'; appendAudit(request,`Production paused at ${request.workMinutes} mins`); }
export function recordProduction(state, request) { request.workMinutes=currentWorkMinutes(request); request.timerStartedAt=null; const previouslyRecorded=request.productionRecordedMinutes || 0; const additionalMinutes=Math.max(0,request.workMinutes-previouslyRecorded); state.productionByResearcher ||= {}; state.productionByResearcher[request.researcher]=(state.productionByResearcher[request.researcher] || 0) + additionalMinutes; request.productionRecordedMinutes=request.workMinutes; request.productionRecorded=true; }
export function moveToArchive(state, request, action) { request.archivedAt=new Date().toISOString(); appendAudit(request,action); state.myRequests=state.myRequests.filter(item=>item.id!==request.id); state.archive.unshift(request); }
