import { escapeHtml, formatDate, icon } from './utils.js';
import { currentWorkMinutes } from './workflow.js';

const fields = [['Request ID','id'],['Requester','requester'],['Designation','designation'],['Region','region'],['Business','business'],['Company','company'],['Request Type','type'],['Priority','priority'],['Deadline','deadline']];
export function renderMyRequests(state) {
  if (!state.myRequests.length) return `<div class="my-requests-head"><h2>My Requests</h2><button class="back-queue" data-open-queue>Back to Queue</button></div><section class="empty-state"><h2>No requests assigned</h2><p>Assign a request from the Queue to start work and open its workspace.</p></section>`;
  return `<div class="my-requests-head"><h2>My Requests <span style="color:#718096;font-size:15px">(${state.myRequests.length})</span></h2><button class="back-queue" data-open-queue>Back to Queue</button></div><div class="table-scroll"><table class="request-table" style="min-width:1150px"><thead><tr><th>Request ID</th><th>Requester</th><th>Company</th><th>Request Type</th><th>Researcher</th><th>QCer</th><th>Priority</th><th>Status</th><th>Deadline</th><th>Workspace</th></tr></thead><tbody>${state.myRequests.map(r=>`<tr><td class="request-id">${r.id}</td><td>${escapeHtml(r.requester)}</td><td>${escapeHtml(r.company)}</td><td>${escapeHtml(r.type)}</td><td>${escapeHtml(r.researcher || '—')}</td><td>${escapeHtml(r.qc || '—')}</td><td><span class="badge priority-${r.priority.toLowerCase()}">${r.priority}</span></td><td>${escapeHtml(r.status)}</td><td>${formatDate(r.deadline)}</td><td><button class="assign" data-open-workspace="${r.id}">Open</button></td></tr>`).join('')}</tbody></table></div>`;
}

export function renderWorkspace(request) {
  return `<div class="my-requests-head"><h2>Request Workspace <span style="color:#718096;font-size:15px">/ ${request.id}</span></h2><button class="back-queue" data-back-myrequests>Back to My Requests</button></div><section class="workspace"><aside class="workspace-panel"><div class="workspace-title">Request Details</div><dl class="detail-list">${fields.map(([label,key])=>`<div class="detail-row"><dt>${label}</dt><dd>${key==='deadline'?formatDate(request[key]):escapeHtml(request[key])}</dd></div>`).join('')}<div class="detail-row"><dt>QC route</dt><dd>${request.requiresQC ? `Required · ${escapeHtml(request.qc)}` : 'Production only'}</dd></div><div class="detail-row"><dt>Description</dt><dd>${escapeHtml(request.description)}</dd></div></dl></aside><section class="workspace-panel"><div class="workspace-title">Work Management</div>${renderWorkStage(request)}${renderComments(request)}<div class="workspace-section"><h3>Attachments</h3><ul class="attachment-list">${request.attachments.length ? request.attachments.map(a=>`<li><span>${escapeHtml(a.name)}</span><span>${escapeHtml(a.addedBy)}</span></li>`).join('') : '<li><span>No attachments added.</span></li>'}</ul><button class="attachment-action" data-add-attachment="${request.id}">${icon('clip',16)} Add attachment record</button></div></section><aside class="workspace-panel"><div class="workspace-title">Audit Trail</div><div class="workspace-section"><ol class="audit-list">${[...request.audit].reverse().map(item=>`<li class="audit-item">${escapeHtml(item.action)}<time class="audit-at">${formatDate(item.at)}</time></li>`).join('')}</ol></div></aside></section>`;
}

function renderWorkStage(request) {
  if (request.workflowStage === 'qc') return `<div class="workspace-section"><h3>QC Review · ${escapeHtml(request.qc)}</h3><div class="eta-box"><span>Research submitted by ${escapeHtml(request.researcher)}</span><strong>${currentWorkMinutes(request)} mins</strong></div><p style="font-size:13px;color:#59687d">Open the QC review popup to select a rating, add comments, use review templates, and decide the outcome.</p><button class="comment-send" data-open-qc="${request.id}">Open QC Review</button></div>`;
  if (request.workflowStage === 'delivery') return `<div class="workspace-section"><h3>Final Delivery</h3><div class="eta-box"><span>QC approved · ready for banker delivery</span><strong>${currentWorkMinutes(request)} mins</strong></div><p style="font-size:13px;color:#59687d">The researcher records final production time and confirms delivery to complete this request.</p><label class="clock-label" style="color:#506078">Final production minutes</label><input class="status-select" type="number" min="0" value="${currentWorkMinutes(request)}" data-work-minutes><button class="comment-send" data-final-delivery="${request.id}">Confirm delivery & complete</button></div>`;
  const worked=currentWorkMinutes(request); return `<div class="workspace-section"><h3>Production · ${request.requiresQC ? 'QC required after research' : 'Production only'}</h3><div class="eta-box"><span>ETA remaining</span><strong>${Math.max(0,request.eta-worked)} mins</strong></div><label class="clock-label" style="color:#506078;margin-top:13px">Production minutes</label><input class="status-select" type="number" min="0" value="${worked}" data-work-minutes><div class="modal-actions" style="justify-content:flex-start"><button class="primary" data-start-work="${request.id}" ${request.timerStartedAt?'disabled':''}>Start work</button><button data-pause-work="${request.id}" ${request.timerStartedAt?'':'disabled'}>Pause</button><button data-submit-research="${request.id}">Complete research</button></div></div>`;
}

function renderComments(request) { return `<div class="workspace-section"><h3>Comments</h3><div class="comments">${request.comments.length ? request.comments.map(c=>`<article class="comment">${escapeHtml(c.text)}<div class="comment-meta">${escapeHtml(c.author)} · ${formatDate(c.at)}</div></article>`).join('') : '<div class="comment">No comments yet.</div>'}</div><textarea class="comment-input" data-comment-input placeholder="Add a work note or requester update..."></textarea><button class="comment-send" data-add-comment="${request.id}">Add Comment</button></div>`; }
